name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: rustup update nightly && rustup default nightly && rustup component add clippy
      
      - name: Build crates
        run: cargo build --verbose
      
      - name: Run tests
        run: cargo test --verbose

      - name: Run clippy
        run: cargo clippy --verbose
