name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo clippy --verbose
